name: |-
  Features branch (Pull request) workflow 
  
  Perform CI - lint `action.yml` and run tests 
  
  ### Usage 
  
  Create in your repo  __`.github/workflows/feature.yaml`__
  
  ```yaml
    name: Feature branch
    on:
      pull_request:
        branches: [ main ]
        types: [opened, synchronize, reopened]
  
    jobs:
      perform:
        uses: cloudposse/github-actions-workflows-github-action-composite/.github/workflows/feature-branch.yml@main
        with:
          organization: "$\{\{ github.event.repository.owner.login \}\}"
          repository: "$\{\{ github.event.repository.name \}\}"
          ref: "$\{\{ github.event.pull_request.head.ref  \}\}"
  ```

on:
  workflow_call:
    inputs:
      organization:
        description: "Repository owner organization (ex. acme for repo acme/example)"
        required: false
        default: ${{ github.event.repository.owner.login }}
        type: string
      repository:
        description: "Repository name (ex. example for repo acme/example)"
        required: false
        default: ${{ github.event.repository.name }}
        type: string
      ref:
        description: "The fully-formed ref of the branch or tag that triggered the workflow run"
        required: false
        default: ${{ github.ref }}
        type: string
      tests-prefix:
        description: "Workflows file name prefix to run as tests"
        required: false
        type: string
        default: 'test-*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  actions: write

jobs:
  ci-readme:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-readme.yml@readme-update
    with:
      # Workaround for https://github.com/community/community/discussions/9099
      # We should switch to nofilter once it's fixed
      filter-mode: diff_context
      suggestions: true
      runs-on: '["ubuntu-latest"]'
      ref: ${{ github.event.pull_request.head.ref }}
      repository: ${{ github.event.pull_request.head.repo.full_name }}

  ci:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-github-action.yml@main
    with:
      organization: ${{ inputs.organization }}
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.ref }}
      tests-prefix: ${{ inputs.tests-prefix }}
