name: Github Action - Main Branch
on:
  workflow_call:
    inputs:
      organization:
        required: true
        type: string
      repository:
        required: true
        type: string
      ref:
        required: false
        default: ${{ github.ref }}
        type: string
      tests-prefix:
        required: false
        type: string
        default: 'test-*'
    secrets:
      github-private-actions-pat:
        required: true

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Workflows
        id: workflows
        shell: bash
        run: |
          TEST_FILES=$(find ./.github/workflows -type f -name "${{ inputs.tests-prefix }}" -exec basename {} \; | jq -MRc -s '. | split("\n") | map(select(. != ""))')
          echo "list=${TEST_FILES}" >> $GITHUB_OUTPUT

    outputs:
      tests: ${{ steps.workflows.outputs.list }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: YAML file validation
        uses: mpoc/nexus-validate-using-remote-schema-action@main
        with:
          api-endpoint: https://json.schemastore.org/github-action.json
          yaml-file: action.yml

  test:
    runs-on: ubuntu-latest
    if: ${{ needs.context.outputs.tests != '[]'  }}
    strategy:
      matrix:
        env: ${{ fromJson(needs.context.outputs.tests) }}
    needs: [ lint, context ]
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: ${{ inputs.organization }}
          repo: ${{ inputs.repository }}
          github_token: ${{ secrets.github-private-actions-pat }}
          workflow_file_name: ${{ matrix.env }}
          ref: ${{ inputs.ref }}
          wait_interval: 10
          client_payload: '{}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true

  draft_release:
    name: draft release
    runs-on: ubuntu-latest
    needs: [ test, lint ]
    if: ${{ always() && ( needs.test.result == 'success' || needs.test.result == 'skipped' ) && needs.lint.result == 'success' }}
    permissions:
      contents: write
    steps:
      - name: Create/Update Draft release
        uses: release-drafter/release-drafter@v5
        with:
          publish: false
          prerelease: false
          config-name: configs/draft-release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
