name: |-
  Main branch workflow
  
  Lint `action.yml`, run tests and draft release
  
  ### Usage 
  
  Create in your repo  __`.github/workflows/main.yaml`__
  
  ```yaml
    name: Main branch
    on:
      push:
        branches: [ main ]
  
    permissions:
      contents: write
  
    jobs:
      perform:
        uses: cloudposse/github-actions-workflows-github-action-composite/.github/workflows/main-branch.yml@main
        with:
          organization: "$\{\{ github.event.repository.owner.login \}\}"
          repository: "$\{\{ github.event.repository.name \}\}"
  ```

on:
  workflow_call:
    inputs:
      organization:
        description: "Repository owner organization (ex. acme for repo acme/example)"
        required: false
        default: ${{ github.event.repository.owner.login }}
        type: string
      repository:
        description: "Repository name (ex. example for repo acme/example)"
        required: false
        default: ${{ github.event.repository.name }}
        type: string
      ref:
        description: "The fully-formed ref of the branch or tag that triggered the workflow run"
        required: false
        default: ${{ github.ref }}
        type: string
      tests-prefix:
        description: "Workflows file name prefix to run as tests"
        required: false
        type: string
        default: 'test-*'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Workflows
        id: workflows
        shell: bash
        run: |
          TEST_FILES=$(find ./.github/workflows -type f -name "${{ inputs.tests-prefix }}" -exec basename {} \; | jq -MRc -s '. | split("\n") | map(select(. != ""))')
          echo "list=${TEST_FILES}" >> $GITHUB_OUTPUT

    outputs:
      tests: ${{ steps.workflows.outputs.list }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: YAML file validation
        uses: mpoc/nexus-validate-using-remote-schema-action@main
        with:
          api-endpoint: https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-action.json
          yaml-file: action.yml

  test:
    runs-on: ubuntu-latest
    if: ${{ needs.context.outputs.tests != '[]'  }}
    strategy:
      matrix:
        env: ${{ fromJson(needs.context.outputs.tests) }}
    needs: [ lint, context ]
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: ${{ inputs.organization }}
          repo: ${{ inputs.repository }}
          github_token: ${{ github.token }}
          workflow_file_name: ${{ matrix.env }}
          ref: ${{ inputs.ref }}
          wait_interval: 10
          client_payload: '{}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true

  draft_release:
    needs: [ test, lint ]
    if: ${{ always() && ( needs.test.result == 'success' || needs.test.result == 'skipped' ) && needs.lint.result == 'success' }}
    uses: cloudposse/.github/.github/workflows/shared-auto-release.yml@main
    with:
      publish: true
    secrets: inherit
